# Regular Expressions

In [3]:
import re

In [25]:
doc = "Regular expressions can be concatenated to form new regular expressions; 08 " \
"if A and B are both regular expressions, then AB is also a regular expression. 12 " \
"In general, if a string p matches A and another string q matches B, the string pq will match AB. 09 " \
"This holds unless A or B contain low precedence operations; boundary conditions between A and B; 19 " \
"or have numbered group references. 22 Thus, complex expressions can easily be constructed 1454 " \
"from simpler primitive expressions like the ones described here. Please email us at aaa@bbb.cc for more info."

In [6]:
re.search('AB', doc)

<re.Match object; span=(122, 124), match='AB'>

In [7]:
doc[122:124]

'AB'

In [8]:
re.findall('AB', doc)

['AB', 'AB']

In [9]:
re.search('[0-9]', doc)

<re.Match object; span=(73, 74), match='0'>

In [10]:
doc[73:74]

'0'

In [11]:
re.findall('[0-9]', doc)

['0', '8', '1', '2', '0', '9', '1', '9', '2', '2', '1', '4', '5']

In [12]:
re.findall('[0-9][0-9]', doc)

['08', '12', '09', '19', '22', '14']

In [15]:
re.findall('[0-9]*[0-9]', doc)

['08', '12', '09', '19', '22', '1454']

In [22]:
re.findall('a[a-z]{2}\s', doc)

['and ', 'are ', 'and ', 'ain ', 'ary ', 'and ', 'ave ']

In [23]:
re.search('\.$', doc)

<re.Match object; span=(516, 517), match='.'>

In [26]:
re.search('[a-zA-Z0-9]+@[a-zA-Z0-9]+\.[a-zA-Z]{2,3}', doc)

<re.Match object; span=(537, 547), match='aaa@bbb.cc'>

In [27]:
doc[537:547]

'aaa@bbb.cc'

# NumPy

In [28]:
import numpy as np

In [30]:
values = np.array([23, 56, 123, 44, 231, 12, 109, 134, 28])

In [31]:
values.mean()

84.44444444444444

In [32]:
values.sum()

760

In [33]:
values2d = values.reshape(3, 3)

In [34]:
values2d

array([[ 23,  56, 123],
       [ 44, 231,  12],
       [109, 134,  28]])

In [35]:
np.sort(values)

array([ 12,  23,  28,  44,  56, 109, 123, 134, 231])

In [36]:
values

array([ 23,  56, 123,  44, 231,  12, 109, 134,  28])